version: 2
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    user: root
    ports:
      - 10080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME:/home
    environment:
      - JENKINS_OPTS=--httpPort=8080 --httpsPort=8443
      - JAVA_OPTS=-Xmx2048m -XX:MaxPermSize=512m -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=3600
volumes:
  jenkins_data:
    driver: local